<?php
/**
 * Copyright © 2021 Grability. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /* @var $block \Grability\Mobu\Block\System\Config\ButtonSync */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        //var collectSpan = jQuery('#collect_span');

        jQuery('#button_sync').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>store/<?php echo $block->resolveCurrentStoreId() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {console.log("creado...");
                    /*jQuery('#loader_synckButton').css('display','block');*/
                    jQuery('body').trigger('processStart');
                },
                onSuccess: function(response) {console.log(response);
                    jQuery('body').trigger('processStop');
                },
                onError: function(data) {
                    jQuery('body').trigger('processStop');
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>
